# starship.toml - https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#format = """$character"""       # minimal left prompt
# requires ble.sh https://github.com/akinomyoga/ble.sh for bash, with far reaching consequences
#right_format = """$all"""

add_newline = false             # I like minimal
continuation_prompt = '▶▶ '

[character]
error_symbol = '[✗](bold fg:red)'
success_symbol = '[▶](bold fg:green)'

[line_break]
disabled = true                 # I like old style

[aws]
disabled = true

[cmd_duration]                  # this seems to accumulate idle time
format = '[$duration]($style) '
disabled = true

[directory]
truncation_symbol = ''
use_logical_path = false

[directory.substitutions]
'/Volumes/CM' = 'CM'

[direnv]
format = '[$symbol$loaded]($style) '
symbol = "e"
loaded_msg = "󰄲"
unloaded_msg = "✗"
disabled = true                 # seems to cause line editting corruption

[docker_context]
format = '[$symbol]($style) '
disabled = false

[gcloud]
disabled = true

[golang]
disabled = true

[git_branch]
#format = '[$symbol$branch(:$remote_branch)]($style) '
format = '[$symbol$branch]($style) '
style = 'bold purple'

[git_status]
disabled = false
style = 'bold purple'

[java]
format = '[$symbol]($style) '
[localip]
disabled = true
ssh_only = false

[lua]
format = '[$symbol]($style)'
disabled = true

[nodejs]
format = '[$symbol]($style)'
disabled = true

[os]
format = '[$symbol]($style)'
disabled = false

[os.symbols]
Macos = ' ' # plainer '' - broken in some nerdfonts; alternative: '⌘'

[package]
format = '[$symbol]($style) '
disabled = false

[perl]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
disabled = false
detect_extensions = []
# prevent random .py files, eg., in ~/Documents, from triggering

[shell]
bash_indicator = 'b'
zsh_indicator = 'z'
disabled = true
# helpful when debbuging bash vs. zsh compatibility

[sudo]
disabled = false
format = '[$symbol]($style) '
style = 'bold red'
symbol = "#"

[username]
disabled = false
show_always = true
format = '[$user]($style) '
aliases = { "jwd" = "" }

[custom.foo]                    # example as a reminder
command = 'echo foo' # shows output of command
detect_files = ['foo'] # can specify filters but wildcards are not supported
#when = ''' test "$HOME" = "$PWD" '''
format = '[$output ]($style)'
